---
# tasks file for ansible-sudoers
- name: Set sudoers settings...
  become: true
  community.general.sudoers:
    commands: "{{ item.commands | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    host: "{{ item.host | default(sudoers_default__host) | default(omit) }}"
    name: "{{ item.name }}"
    nopassword: "{{ item.nopassword | default(sudoers_default__nopassword) | default(omit) }}"
    runas: "{{ item.runas | default(omit) }}"
    setenv: "{{ item.setenv | default(omit) }}"
    state: "{{ item.state | default(sudoers_default__state) | default(omit) }}"
    sudoers_path: "{{ item.sudoers_path | default(sudoers_default__sudoers_path) | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    validation: "{{ item.validation | default(sudoers_default__validation) | default(omit) }}"
  with_items: "{{ sudoers }}"
  tags:
    - config
    - setting
